# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Format
format = """
[](red)$os$username$hostname[](red) \
[](peach)$directory[](peach) \
$git_branch\
$character"""
add_newline = true

right_format = """
$status\
$cmd_duration\
$git_state\
$git_metrics
"""

# Current theme
palette = "catppuccin_mocha"

[hostname]
ssh_only = false
disabled = false
format = '[@$hostname]($style)'
style = "bg:red fg:crust"

[custom.jj]
description = "The current jj status"
when = "jj --ignore-working-copy root"
shell = []
detect_folders = [".jj"]
require_repo = true
ignore_timeout = true
symbol = ""
style = "bg:yellow"
format = '[](yellow)[[$symbol $output](fg:crust bg:yellow)]($style)[](yellow) '
command = '''
jj show @ --no-patch --ignore-working-copy --color never --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "󰺇"),
      if(divergent, "󰺆"),
      if(hidden, "󰊠"),
      if(immutable, "󰌾"),
    ),
    if(empty, "(empty)"),
    coalesce(
      truncate_end(29, description.first_line(), "…"),
      "(no description set)",
    ),
  )
'
'''

[git_metrics]
disabled = false
added_style = "bg:mantle fg:green"
deleted_style = "bg:mantle fg:red"
only_nonzero_diffs = false
format = ' [](mantle)[+$added]($added_style)[/](bg:mantle)[-$deleted]($deleted_style)[](mantle)'

[localip]
ssh_only = false
format = '[@$localipv4]($style)'
style = "bg:red fg:crust"
disabled = false

[cmd_duration]
show_milliseconds = true
format = " [](lavender)[ $duration]($style)[](lavender)"
style = "bg:lavender fg:crust"
disabled = false
min_time = 0

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[](yellow)[[$symbol $branch](fg:crust bg:yellow)]($style)[](yellow) '

[git_state]
disabled = false
format = ' [](yellow)[$state( $progress_current/$progress_total)]($style)[](yellow)'
style = "bg:yellow fg:crust"

[status]
disabled = false
format = "[](mauve)[$symbol $status]($style)[](mauve)"
symbol = "✗"
success_symbol = "✓"
sigint_symbol = "⚡"
signal_symbol = "⚡"
not_executable_symbol = ""
not_found_symbol = ""
style = "bg:mauve fg:crust"

[directory]
style = "bg:peach fg:crust"
format = "[$read_only$path]($style)"
truncation_length = 8
read_only = " "
truncation_symbol = ""

[character]
format = "$symbol "
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold maroon)'
vimcmd_symbol = '[V](bold green)'

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[os]
disabled = false
format = "[$symbol]($style)"
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# Themes
# Catppuccin Mocha theme
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
